# Generated by Django 3.2.9 on 2023-10-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
