# Generated by Django 4.2.6 on 2023-10-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_auto_20231022_2012"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="books",),
        migrations.AddField(
            model_name="wishlist",
            name="books",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wishlist.book",
            ),
            preserve_default=False,
        ),
    ]
