# Generated by Django 4.2.6 on 2023-10-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20231025_1931"),
        ("wishlist", "0003_remove_wishlist_books_wishlist_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
        migrations.DeleteModel(name="Book",),
    ]
