# Generated by Django 3.2.9 on 2023-10-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20231029_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='notes',
        ),
    ]
