# Generated by Django 4.2.6 on 2023-10-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_account_is_premium"),
        ("wishlist", "0004_alter_wishlist_books_delete_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.account"
            ),
        ),
    ]
