# Generated by Django 4.2.6 on 2023-10-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('cart', models.ManyToManyField(related_name='cart', to='book.book')),
                ('owned_books', models.ManyToManyField(related_name='owned_books', to='book.book')),
            ],
        ),
    ]
