# Generated by Django 4.2.4 on 2023-10-26 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_account_is_premium'),
        ('book', '0002_auto_20231025_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
                ('cart', models.ManyToManyField(to='book.book')),
            ],
        ),
    ]
