# Generated by Django 4.2.6 on 2023-10-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daftar_belanja", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="shoppingcart", name="cart",),
    ]
