# Generated by Django 4.2.4 on 2023-10-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231025_1931'),
        ('daftar_belanja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.book')),
                ('amount', models.IntegerField()),
            ],
            bases=('book.book',),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart',
            field=models.ManyToManyField(to='daftar_belanja.orderedbook'),
        ),
    ]
