# Generated by Django 4.2.4 on 2023-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231025_1931'),
        ('daftar_belanja', '0002_orderedbook_alter_shoppingcart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart',
            field=models.ManyToManyField(to='book.book'),
        ),
        migrations.DeleteModel(
            name='OrderedBook',
        ),
    ]
