# Generated by Django 4.2.4 on 2023-10-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_premium',
            field=models.CharField(max_length=3),
        ),
    ]
