# Generated by Django 3.2.9 on 2023-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_premium',
            field=models.CharField(max_length=3),
        ),
    ]
