# Generated by Django 4.2.6 on 2023-10-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
