# Generated by Django 4.2.5 on 2023-10-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rak_buku', '0001_initial'),
        ('book', '0002_auto_20231025_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rak',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rak_buku.rak'),
            preserve_default=False,
        ),
    ]
