# Generated by Django 3.2.21 on 2023-10-29 10:47

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):

    def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "book.json")

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
