# Generated by Django 4.2.6 on 2023-11-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231029_1047'),
        ('book', '0003_auto_20231128_2122'),
    ]

    operations = [
    ]
