# Generated by Django 4.2.5 on 2023-10-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_user'),
        ('book', '0005_remove_book_rak'),
    ]

    operations = [
    ]
